### ISSUE TITLE
読み込んだVRMを保存して選択できるようにしてほしい

### ISSUE THREAD

**Issue by KenWatanabe-G** [creativeIKEP/HolisticMotionCapture#1]
背景と同じように読み込んだVRMをコピーしてlocalに保持しておき、セレクトボックスで選択できるようにしてほしいです！
+ 前回選択したVRMを次回起動時に自動で選択するようになっているととても便利です。

**Comment by creativeIKEP** [comment]
@KenWatanabe-G 
ご要望ありがとうございます。
比較的簡単な実装で可能であり、かつ、自分も良い機能だと思ったため実装させていただきました。
v1.1.0にてリリースしましたので、ご確認ください。
